apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: rosilva2018/python-app:latest
        ports:
        - containerPort: 80
        env:
        - name: LOKI_URL
          value: "http://loki:3100"
